import angular  from 'angular';
import uiRouter from 'angular-ui-router';

// Import our app functionaity
import Common     from './common';
import Components from './components';
import Layouts    from './layouts';

// Import our App configs.
import AppConfig     from './config/app.config';
import AppConstants  from './config/app.constants';
import AppRun        from './config/app.run';
import AppController from './config/app.controller';
// Import our templates file (generated by Gulp).
import AppTemplates  from './config/app.templates';

let dependencies = [
  uiRouter,
  AppTemplates.name,
  Layouts.name,
  Common.name,
  Components.name
];

// Mount on window for testing
window.app = angular
  .module( 'app', dependencies )
  .constant( 'AppConstants', AppConstants )
  .controller( 'AppController', AppController )
  .config( AppConfig )
  .run( AppRun );

// Bootstrap our app manually
angular
  .element( document )
  .ready( () => {
    angular.bootstrap( document, ['app'], {
      strictDi: true
    });
  });
